language: java

jdk:
 - oraclejdk8

before_install:
 - wget http://search.maven.org/remotecontent?filepath=junit/junit/4.12/junit-4.12.jar
 - wget http://search.maven.org/remotecontent?filepath=org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar
 - export CLASSPATH="./"
